# Generated by Django 5.0.6 on 2024-06-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
