# Generated by Django 5.0.6 on 2024-06-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_client_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
