# Generated by Django 5.0.6 on 2024-06-03 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('street_number', models.IntegerField()),
                ('city', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('property_listing', models.CharField(max_length=50)),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.housing')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.status')),
            ],
        ),
    ]
