# Generated by Django 5.0.6 on 2024-06-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default=2312, upload_to='img'),
            preserve_default=False,
        ),
    ]
