# Generated by Django 5.0.6 on 2024-06-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='bath',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='sqft',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
