# Generated by Django 5.0.6 on 2024-06-14 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_client_password'),
        ('property', '0003_property_bad_property_bath_property_sqft'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authenticate.client'),
            preserve_default=False,
        ),
    ]
