# Generated by Django 5.0.6 on 2024-06-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='client',
        ),
    ]
