# Generated by Django 5.0.6 on 2024-06-14 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_client_password'),
        ('property', '0006_property_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authenticate.client'),
        ),
    ]
